name: Weekly Broken Link Checker

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 2 * * 0" # Runs every Sunday at 2 AM UTC

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run linkinator
        id: linkinator
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: https://stebre.ch
          recurse: true
          markdown: false
          verbosity: error
        continue-on-error: true

      - name: Create report file
        id: create_report
        run: |
          echo "## Broken Links Found" > broken-links.md
          echo "" >> broken-links.md
          jq -r '.links[] | select(.state=="BROKEN" and .status== "Error") | "* [\(.url)](\(.url)) - \(.status)"' ${{ steps.linkinator.outputs.results }} >> broken-links.md
          cat broken-links.md

      - name: Create Issue
        run: |
          broken_links=$(cat broken-links.md)
          if [[ -n "$broken_links" ]]; then
            issue_data='{
              "title": "Broken Links Found",
              "body": "'"$broken_links"'"
            }'
            curl \
              -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d "$issue_data" \
              "https://api.github.com/repos/${{ github.repository }}/issues"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
