name: Weekly Broken Link Checker

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 2 */2 * *" # Runs every other Sunday at 2 AM UTC

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run linkinator
        id: linkinator
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: https://stebre.ch/en/lesezeichen
          recurse: false
          markdown: false
        continue-on-error: true

      - name: Save output to JSON file
        run: |
          echo '${{ steps.linkinator.outputs.results }}' > linkinator-results.json

      - name: Create Issue
        run: |
          broken_links=$(node -e "
            const fs = require('fs');
            const input = JSON.parse(fs.readFileSync('linkinator-results.json', 'utf-8'));
            const brokenLinks = input.links.filter(link => link.state === 'BROKEN');
            console.log(brokenLinks.map(link => link.url).join('\n'));
          ")
          if [[ -n "$broken_links" ]]; then
            issue_data='{
              "title": "Broken Links Found",
              "body": "'"$broken_links"'"
            }'
            curl \
              -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d "$issue_data" \
              "https://api.github.com/repos/${{ github.repository }}/issues"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
